# Generated by Django 3.2.7 on 2022-01-03 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('odometer', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=25)),
                ('system_description', models.TextField(blank=True)),
                ('vehicle_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehinanceApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=25)),
                ('component_description', models.TextField(blank=True)),
                ('system_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehinanceApp.system')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_interval', models.PositiveIntegerField(default=0)),
                ('time_interval', models.PositiveIntegerField(default=0)),
                ('activity_description', models.TextField(blank=True)),
                ('component_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehinanceApp.component')),
            ],
        ),
    ]
