# Generated by Django 3.2.7 on 2022-01-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='component_fk',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='system_fk',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='vehicle_fk',
            new_name='vehicle',
        ),
    ]
